version: "3.8"
# name: ts-nestjs-prisma-sqlserver-docker # nofing

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    restart: on-failure
    networks:
      - backend
    volumes:
      - ../..:/workspaces:cached
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2.0GB'

networks:
  backend:

